// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk/models/shared"
	"net/http"
)

type CreateKanbanBoardResponse struct {
	// Successfully created board
	Board *shared.Board
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *CreateKanbanBoardResponse) GetBoard() *shared.Board {
	if c == nil {
		return nil
	}
	return c.Board
}

func (c *CreateKanbanBoardResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateKanbanBoardResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateKanbanBoardResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}
