// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteKanbanBoardRequest struct {
	BoardID string `pathParam:"style=simple,explode=false,name=boardId"`
}

func (o *DeleteKanbanBoardRequest) GetBoardID() string {
	if o == nil {
		return ""
	}
	return o.BoardID
}

type DeleteKanbanBoardResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteKanbanBoardResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteKanbanBoardResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteKanbanBoardResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
