// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteKanbanBoardRequest struct {
	BoardID string `pathParam:"style=simple,explode=false,name=boardId"`
}

func (d *DeleteKanbanBoardRequest) GetBoardID() string {
	if d == nil {
		return ""
	}
	return d.BoardID
}

type DeleteKanbanBoardResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (d *DeleteKanbanBoardResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteKanbanBoardResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteKanbanBoardResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}
