// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk/models/shared"
	"net/http"
)

type ExecuteFlowsQueryResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Query results
	FlowsQueryResult *shared.FlowsQueryResult
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ExecuteFlowsQueryResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ExecuteFlowsQueryResponse) GetFlowsQueryResult() *shared.FlowsQueryResult {
	if o == nil {
		return nil
	}
	return o.FlowsQueryResult
}

func (o *ExecuteFlowsQueryResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ExecuteFlowsQueryResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
