// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk/internal/utils"
	"net/http"
)

type FlowsAutocompleteRequest struct {
	// Autocomplete attribute
	Attribute string `queryParam:"style=form,explode=true,name=attribute"`
	// Starting offset for pagination
	From *int64 `default:"0" queryParam:"style=form,explode=true,name=from"`
	// Input to autocomplete
	Input *string `queryParam:"style=form,explode=true,name=input"`
	// Maximum number of results to return
	Size *int64 `default:"25" queryParam:"style=form,explode=true,name=size"`
}

func (f FlowsAutocompleteRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FlowsAutocompleteRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, []string{"attribute"}); err != nil {
		return err
	}
	return nil
}

func (o *FlowsAutocompleteRequest) GetAttribute() string {
	if o == nil {
		return ""
	}
	return o.Attribute
}

func (o *FlowsAutocompleteRequest) GetFrom() *int64 {
	if o == nil {
		return nil
	}
	return o.From
}

func (o *FlowsAutocompleteRequest) GetInput() *string {
	if o == nil {
		return nil
	}
	return o.Input
}

func (o *FlowsAutocompleteRequest) GetSize() *int64 {
	if o == nil {
		return nil
	}
	return o.Size
}

type ResultsType string

const (
	ResultsTypeStr      ResultsType = "str"
	ResultsTypeBoolean  ResultsType = "boolean"
	ResultsTypeMapOfAny ResultsType = "mapOfAny"
)

type Results struct {
	Str      *string        `queryParam:"inline" name:"results"`
	Boolean  *bool          `queryParam:"inline" name:"results"`
	MapOfAny map[string]any `queryParam:"inline" name:"results"`

	Type ResultsType
}

func CreateResultsStr(str string) Results {
	typ := ResultsTypeStr

	return Results{
		Str:  &str,
		Type: typ,
	}
}

func CreateResultsBoolean(boolean bool) Results {
	typ := ResultsTypeBoolean

	return Results{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateResultsMapOfAny(mapOfAny map[string]any) Results {
	typ := ResultsTypeMapOfAny

	return Results{
		MapOfAny: mapOfAny,
		Type:     typ,
	}
}

func (u *Results) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = ResultsTypeStr
		return nil
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		u.Boolean = &boolean
		u.Type = ResultsTypeBoolean
		return nil
	}

	var mapOfAny map[string]any = map[string]any{}
	if err := utils.UnmarshalJSON(data, &mapOfAny, "", true, nil); err == nil {
		u.MapOfAny = mapOfAny
		u.Type = ResultsTypeMapOfAny
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Results", string(data))
}

func (u Results) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.MapOfAny != nil {
		return utils.MarshalJSON(u.MapOfAny, "", true)
	}

	return nil, errors.New("could not marshal union type Results: all fields are null")
}

// FlowsAutocompleteResponseBody - Success
type FlowsAutocompleteResponseBody struct {
	// Total number of matching items available
	Hits    float64   `json:"hits"`
	Results []Results `json:"results"`
}

func (o *FlowsAutocompleteResponseBody) GetHits() float64 {
	if o == nil {
		return 0.0
	}
	return o.Hits
}

func (o *FlowsAutocompleteResponseBody) GetResults() []Results {
	if o == nil {
		return []Results{}
	}
	return o.Results
}

type FlowsAutocompleteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	Object *FlowsAutocompleteResponseBody
}

func (o *FlowsAutocompleteResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *FlowsAutocompleteResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *FlowsAutocompleteResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *FlowsAutocompleteResponse) GetObject() *FlowsAutocompleteResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
