// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk/internal/utils"
	"net/http"
)

type FlowsAutocompleteRequest struct {
	// Autocomplete attribute
	Attribute string `queryParam:"style=form,explode=true,name=attribute"`
	// Starting offset for pagination
	From *int64 `default:"0" queryParam:"style=form,explode=true,name=from"`
	// Input to autocomplete
	Input *string `queryParam:"style=form,explode=true,name=input"`
	// Maximum number of results to return
	Size *int64 `default:"25" queryParam:"style=form,explode=true,name=size"`
}

func (f FlowsAutocompleteRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FlowsAutocompleteRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, []string{"attribute"}); err != nil {
		return err
	}
	return nil
}

func (f *FlowsAutocompleteRequest) GetAttribute() string {
	if f == nil {
		return ""
	}
	return f.Attribute
}

func (f *FlowsAutocompleteRequest) GetFrom() *int64 {
	if f == nil {
		return nil
	}
	return f.From
}

func (f *FlowsAutocompleteRequest) GetInput() *string {
	if f == nil {
		return nil
	}
	return f.Input
}

func (f *FlowsAutocompleteRequest) GetSize() *int64 {
	if f == nil {
		return nil
	}
	return f.Size
}

type ResultsType string

const (
	ResultsTypeStr      ResultsType = "str"
	ResultsTypeBoolean  ResultsType = "boolean"
	ResultsTypeMapOfAny ResultsType = "mapOfAny"
)

type Results struct {
	Str      *string        `queryParam:"inline,name=results"`
	Boolean  *bool          `queryParam:"inline,name=results"`
	MapOfAny map[string]any `queryParam:"inline,name=results"`

	Type ResultsType
}

func CreateResultsStr(str string) Results {
	typ := ResultsTypeStr

	return Results{
		Str:  &str,
		Type: typ,
	}
}

func CreateResultsBoolean(boolean bool) Results {
	typ := ResultsTypeBoolean

	return Results{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateResultsMapOfAny(mapOfAny map[string]any) Results {
	typ := ResultsTypeMapOfAny

	return Results{
		MapOfAny: mapOfAny,
		Type:     typ,
	}
}

func (u *Results) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ResultsTypeStr,
			Value: &str,
		})
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ResultsTypeBoolean,
			Value: &boolean,
		})
	}

	var mapOfAny map[string]any = map[string]any{}
	if err := utils.UnmarshalJSON(data, &mapOfAny, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ResultsTypeMapOfAny,
			Value: mapOfAny,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Results", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestCandidate(candidates)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Results", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ResultsType)
	switch best.Type {
	case ResultsTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case ResultsTypeBoolean:
		u.Boolean = best.Value.(*bool)
		return nil
	case ResultsTypeMapOfAny:
		u.MapOfAny = best.Value.(map[string]any)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Results", string(data))
}

func (u Results) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.MapOfAny != nil {
		return utils.MarshalJSON(u.MapOfAny, "", true)
	}

	return nil, errors.New("could not marshal union type Results: all fields are null")
}

// FlowsAutocompleteResponseBody - Success
type FlowsAutocompleteResponseBody struct {
	// Total number of matching items available
	Hits    float64   `json:"hits"`
	Results []Results `json:"results"`
}

func (f *FlowsAutocompleteResponseBody) GetHits() float64 {
	if f == nil {
		return 0.0
	}
	return f.Hits
}

func (f *FlowsAutocompleteResponseBody) GetResults() []Results {
	if f == nil {
		return []Results{}
	}
	return f.Results
}

type FlowsAutocompleteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	Object *FlowsAutocompleteResponseBody
}

func (f *FlowsAutocompleteResponse) GetContentType() string {
	if f == nil {
		return ""
	}
	return f.ContentType
}

func (f *FlowsAutocompleteResponse) GetStatusCode() int {
	if f == nil {
		return 0
	}
	return f.StatusCode
}

func (f *FlowsAutocompleteResponse) GetRawResponse() *http.Response {
	if f == nil {
		return nil
	}
	return f.RawResponse
}

func (f *FlowsAutocompleteResponse) GetObject() *FlowsAutocompleteResponseBody {
	if f == nil {
		return nil
	}
	return f.Object
}
