// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk/models/shared"
	"net/http"
)

type GetKanbanBoardRequest struct {
	BoardID string `pathParam:"style=simple,explode=false,name=boardId"`
}

func (g *GetKanbanBoardRequest) GetBoardID() string {
	if g == nil {
		return ""
	}
	return g.BoardID
}

type GetKanbanBoardResponse struct {
	// Successfully retrieved board
	Board *shared.Board
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetKanbanBoardResponse) GetBoard() *shared.Board {
	if g == nil {
		return nil
	}
	return g.Board
}

func (g *GetKanbanBoardResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetKanbanBoardResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetKanbanBoardResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
