// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk/models/shared"
	"net/http"
)

// Filter boards by ownership type. If not provided, returns all accessible boards.
type Filter string

const (
	FilterOwned  Filter = "owned"
	FilterShared Filter = "shared"
)

func (e Filter) ToPointer() *Filter {
	return &e
}
func (e *Filter) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "owned":
		fallthrough
	case "shared":
		*e = Filter(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Filter: %v", v)
	}
}

type GetKanbanBoardsRequest struct {
	// Filter boards by ownership type. If not provided, returns all accessible boards.
	Filter *Filter `queryParam:"style=form,explode=true,name=filter"`
}

func (g *GetKanbanBoardsRequest) GetFilter() *Filter {
	if g == nil {
		return nil
	}
	return g.Filter
}

type GetKanbanBoardsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successfully retrieved boards
	Classes []shared.BoardSummary
}

func (g *GetKanbanBoardsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetKanbanBoardsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetKanbanBoardsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetKanbanBoardsResponse) GetClasses() []shared.BoardSummary {
	if g == nil {
		return nil
	}
	return g.Classes
}
