// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk/models/shared"
	"net/http"
)

type PatchKanbanBoardRequestBody struct {
	Description *string `json:"description,omitempty"`
	// Array of user IDs who have full ownership rights for this board (view, edit, delete)
	Owners        []string `json:"owners,omitempty"`
	SharedWith    []string `json:"shared_with,omitempty"`
	SharedWithOrg *bool    `json:"shared_with_org,omitempty"`
	Title         *string  `json:"title,omitempty"`
}

func (o *PatchKanbanBoardRequestBody) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *PatchKanbanBoardRequestBody) GetOwners() []string {
	if o == nil {
		return nil
	}
	return o.Owners
}

func (o *PatchKanbanBoardRequestBody) GetSharedWith() []string {
	if o == nil {
		return nil
	}
	return o.SharedWith
}

func (o *PatchKanbanBoardRequestBody) GetSharedWithOrg() *bool {
	if o == nil {
		return nil
	}
	return o.SharedWithOrg
}

func (o *PatchKanbanBoardRequestBody) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

type PatchKanbanBoardRequest struct {
	RequestBody *PatchKanbanBoardRequestBody `request:"mediaType=application/json"`
	BoardID     string                       `pathParam:"style=simple,explode=false,name=boardId"`
}

func (o *PatchKanbanBoardRequest) GetRequestBody() *PatchKanbanBoardRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *PatchKanbanBoardRequest) GetBoardID() string {
	if o == nil {
		return ""
	}
	return o.BoardID
}

type PatchKanbanBoardResponse struct {
	// Successfully patched board
	Board *shared.Board
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PatchKanbanBoardResponse) GetBoard() *shared.Board {
	if o == nil {
		return nil
	}
	return o.Board
}

func (o *PatchKanbanBoardResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchKanbanBoardResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchKanbanBoardResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
