// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk/models/shared"
	"net/http"
)

type PatchKanbanBoardRequestBody struct {
	Description   *string  `json:"description,omitempty"`
	SharedWith    []string `json:"shared_with,omitempty"`
	SharedWithOrg *bool    `json:"shared_with_org,omitempty"`
	Title         *string  `json:"title,omitempty"`
}

func (p *PatchKanbanBoardRequestBody) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PatchKanbanBoardRequestBody) GetSharedWith() []string {
	if p == nil {
		return nil
	}
	return p.SharedWith
}

func (p *PatchKanbanBoardRequestBody) GetSharedWithOrg() *bool {
	if p == nil {
		return nil
	}
	return p.SharedWithOrg
}

func (p *PatchKanbanBoardRequestBody) GetTitle() *string {
	if p == nil {
		return nil
	}
	return p.Title
}

type PatchKanbanBoardRequest struct {
	RequestBody *PatchKanbanBoardRequestBody `request:"mediaType=application/json"`
	BoardID     string                       `pathParam:"style=simple,explode=false,name=boardId"`
}

func (p *PatchKanbanBoardRequest) GetRequestBody() *PatchKanbanBoardRequestBody {
	if p == nil {
		return nil
	}
	return p.RequestBody
}

func (p *PatchKanbanBoardRequest) GetBoardID() string {
	if p == nil {
		return ""
	}
	return p.BoardID
}

type PatchKanbanBoardResponse struct {
	// Successfully patched board
	Board *shared.Board
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (p *PatchKanbanBoardResponse) GetBoard() *shared.Board {
	if p == nil {
		return nil
	}
	return p.Board
}

func (p *PatchKanbanBoardResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PatchKanbanBoardResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PatchKanbanBoardResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}
