// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk/models/shared"
	"net/http"
)

type UpdateKanbanBoardRequest struct {
	Board   *shared.Board `request:"mediaType=application/json"`
	BoardID string        `pathParam:"style=simple,explode=false,name=boardId"`
}

func (o *UpdateKanbanBoardRequest) GetBoard() *shared.Board {
	if o == nil {
		return nil
	}
	return o.Board
}

func (o *UpdateKanbanBoardRequest) GetBoardID() string {
	if o == nil {
		return ""
	}
	return o.BoardID
}

type UpdateKanbanBoardResponse struct {
	// Successfully updated board
	Board *shared.Board
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *UpdateKanbanBoardResponse) GetBoard() *shared.Board {
	if o == nil {
		return nil
	}
	return o.Board
}

func (o *UpdateKanbanBoardResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateKanbanBoardResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateKanbanBoardResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
