// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk/internal/utils"
	"time"
)

type BoardSummary struct {
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	CreatedBy   *string    `json:"created_by,omitempty"`
	Description *string    `json:"description,omitempty"`
	ID          *string    `json:"id,omitempty"`
	OrgID       *string    `json:"org_id,omitempty"`
	// Array of user IDs who have full ownership rights for this board (view, edit, delete)
	Owners        any        `json:"owners,omitempty"`
	SharedWith    any        `json:"shared_with,omitempty"`
	SharedWithOrg *bool      `json:"shared_with_org,omitempty"`
	Title         *string    `json:"title,omitempty"`
	UpdatedAt     *time.Time `json:"updated_at,omitempty"`
	UpdatedBy     *string    `json:"updated_by,omitempty"`
}

func (b BoardSummary) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BoardSummary) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BoardSummary) GetCreatedAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.CreatedAt
}

func (b *BoardSummary) GetCreatedBy() *string {
	if b == nil {
		return nil
	}
	return b.CreatedBy
}

func (b *BoardSummary) GetDescription() *string {
	if b == nil {
		return nil
	}
	return b.Description
}

func (b *BoardSummary) GetID() *string {
	if b == nil {
		return nil
	}
	return b.ID
}

func (b *BoardSummary) GetOrgID() *string {
	if b == nil {
		return nil
	}
	return b.OrgID
}

func (b *BoardSummary) GetOwners() any {
	if b == nil {
		return nil
	}
	return b.Owners
}

func (b *BoardSummary) GetSharedWith() any {
	if b == nil {
		return nil
	}
	return b.SharedWith
}

func (b *BoardSummary) GetSharedWithOrg() *bool {
	if b == nil {
		return nil
	}
	return b.SharedWithOrg
}

func (b *BoardSummary) GetTitle() *string {
	if b == nil {
		return nil
	}
	return b.Title
}

func (b *BoardSummary) GetUpdatedAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.UpdatedAt
}

func (b *BoardSummary) GetUpdatedBy() *string {
	if b == nil {
		return nil
	}
	return b.UpdatedBy
}
