// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk/internal/utils"
	"time"
)

type CardConfig struct {
	Fields []string `json:"fields,omitempty"`
}

func (c *CardConfig) GetFields() []string {
	if c == nil {
		return nil
	}
	return c.Fields
}

type Config struct {
	BoardFilter *BoardFilter `json:"board_filter,omitempty"`
	CardConfig  *CardConfig  `json:"card_config,omitempty"`
	Dataset     *string      `json:"dataset,omitempty"`
	SearchQuery *string      `json:"search_query,omitempty"`
	Sorting     *Sorting     `json:"sorting,omitempty"`
	Swimlanes   []Swimlane   `json:"swimlanes,omitempty"`
}

func (c *Config) GetBoardFilter() *BoardFilter {
	if c == nil {
		return nil
	}
	return c.BoardFilter
}

func (c *Config) GetCardConfig() *CardConfig {
	if c == nil {
		return nil
	}
	return c.CardConfig
}

func (c *Config) GetDataset() *string {
	if c == nil {
		return nil
	}
	return c.Dataset
}

func (c *Config) GetSearchQuery() *string {
	if c == nil {
		return nil
	}
	return c.SearchQuery
}

func (c *Config) GetSorting() *Sorting {
	if c == nil {
		return nil
	}
	return c.Sorting
}

func (c *Config) GetSwimlanes() []Swimlane {
	if c == nil {
		return nil
	}
	return c.Swimlanes
}

type Board struct {
	Config      *Config    `json:"config,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	CreatedBy   *string    `json:"created_by,omitempty"`
	Description *string    `json:"description,omitempty"`
	ID          *string    `json:"id,omitempty"`
	OrgID       *string    `json:"org_id,omitempty"`
	// Array of user IDs who have full ownership rights for this board (view, edit, delete)
	Owners        []string   `json:"owners,omitempty"`
	SharedWith    []string   `json:"shared_with,omitempty"`
	SharedWithOrg *bool      `json:"shared_with_org,omitempty"`
	Title         *string    `json:"title,omitempty"`
	UpdatedAt     *time.Time `json:"updated_at,omitempty"`
	UpdatedBy     *string    `json:"updated_by,omitempty"`
}

func (b Board) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *Board) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

<<<<<<< HEAD
func (o *Board) GetConfig() *Config {
	if o == nil {
		return nil
=======
func (b *Board) GetConfig() Config {
	if b == nil {
		return Config{}
>>>>>>> e4c5399c64e244ca50474a583c83147415fedf68
	}
	return b.Config
}

func (b *Board) GetCreatedAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.CreatedAt
}

func (b *Board) GetCreatedBy() *string {
	if b == nil {
		return nil
	}
	return b.CreatedBy
}

func (b *Board) GetDescription() *string {
	if b == nil {
		return nil
	}
	return b.Description
}

func (b *Board) GetID() *string {
	if b == nil {
		return nil
	}
	return b.ID
}

func (b *Board) GetOrgID() *string {
	if b == nil {
		return nil
	}
	return b.OrgID
}

<<<<<<< HEAD
func (o *Board) GetOwners() []string {
	if o == nil {
		return nil
	}
	return o.Owners
}

func (o *Board) GetSharedWith() []string {
	if o == nil {
=======
func (b *Board) GetSharedWith() []string {
	if b == nil {
>>>>>>> e4c5399c64e244ca50474a583c83147415fedf68
		return nil
	}
	return b.SharedWith
}

func (b *Board) GetSharedWithOrg() *bool {
	if b == nil {
		return nil
	}
	return b.SharedWithOrg
}

<<<<<<< HEAD
func (o *Board) GetTitle() *string {
	if o == nil {
		return nil
=======
func (b *Board) GetTitle() string {
	if b == nil {
		return ""
>>>>>>> e4c5399c64e244ca50474a583c83147415fedf68
	}
	return b.Title
}

func (b *Board) GetUpdatedAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.UpdatedAt
}

func (b *Board) GetUpdatedBy() *string {
	if b == nil {
		return nil
	}
	return b.UpdatedBy
}
