// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk/internal/utils"
)

type Combination string

const (
	CombinationAnd Combination = "AND"
	CombinationOr  Combination = "OR"
)

func (e Combination) ToPointer() *Combination {
	return &e
}
func (e *Combination) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "AND":
		fallthrough
	case "OR":
		*e = Combination(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Combination: %v", v)
	}
}

type ItemsType string

const (
	ItemsTypeAny         ItemsType = "any"
	ItemsTypeFilterGroup ItemsType = "FilterGroup"
)

type Items struct {
	Any         any          `queryParam:"inline" name:"items"`
	FilterGroup *FilterGroup `queryParam:"inline" name:"items"`

	Type ItemsType
}

func CreateItemsAny(anyT any) Items {
	typ := ItemsTypeAny

	return Items{
		Any:  anyT,
		Type: typ,
	}
}

func CreateItemsFilterGroup(filterGroup FilterGroup) Items {
	typ := ItemsTypeFilterGroup

	return Items{
		FilterGroup: &filterGroup,
		Type:        typ,
	}
}

func (u *Items) UnmarshalJSON(data []byte) error {

	var filterGroup FilterGroup = FilterGroup{}
	if err := utils.UnmarshalJSON(data, &filterGroup, "", true, nil); err == nil {
		u.FilterGroup = &filterGroup
		u.Type = ItemsTypeFilterGroup
		return nil
	}

	var anyVar any = nil
	if err := utils.UnmarshalJSON(data, &anyVar, "", true, nil); err == nil {
		u.Any = anyVar
		u.Type = ItemsTypeAny
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Items", string(data))
}

func (u Items) MarshalJSON() ([]byte, error) {
	if u.Any != nil {
		return utils.MarshalJSON(u.Any, "", true)
	}

	if u.FilterGroup != nil {
		return utils.MarshalJSON(u.FilterGroup, "", true)
	}

	return nil, errors.New("could not marshal union type Items: all fields are null")
}

type BoardFilter struct {
	Combination Combination `json:"combination"`
	Items       []Items     `json:"items"`
}

func (o *BoardFilter) GetCombination() Combination {
	if o == nil {
		return Combination("")
	}
	return o.Combination
}

func (o *BoardFilter) GetItems() []Items {
	if o == nil {
		return []Items{}
	}
	return o.Items
}
