// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk/internal/utils"
	"time"
)

type CardConfig struct {
	Fields []string `json:"fields,omitempty"`
}

func (o *CardConfig) GetFields() []string {
	if o == nil {
		return nil
	}
	return o.Fields
}

type Config struct {
	BoardFilter *BoardFilter `json:"board_filter,omitempty"`
	CardConfig  *CardConfig  `json:"card_config,omitempty"`
	Dataset     *string      `json:"dataset,omitempty"`
	SearchQuery *string      `json:"search_query,omitempty"`
	Sorting     *Sorting     `json:"sorting,omitempty"`
	Swimlanes   []Swimlane   `json:"swimlanes,omitempty"`
}

func (o *Config) GetBoardFilter() *BoardFilter {
	if o == nil {
		return nil
	}
	return o.BoardFilter
}

func (o *Config) GetCardConfig() *CardConfig {
	if o == nil {
		return nil
	}
	return o.CardConfig
}

func (o *Config) GetDataset() *string {
	if o == nil {
		return nil
	}
	return o.Dataset
}

func (o *Config) GetSearchQuery() *string {
	if o == nil {
		return nil
	}
	return o.SearchQuery
}

func (o *Config) GetSorting() *Sorting {
	if o == nil {
		return nil
	}
	return o.Sorting
}

func (o *Config) GetSwimlanes() []Swimlane {
	if o == nil {
		return nil
	}
	return o.Swimlanes
}

type Board struct {
	Config        *Config    `json:"config,omitempty"`
	CreatedAt     *time.Time `json:"created_at,omitempty"`
	CreatedBy     *string    `json:"created_by,omitempty"`
	Description   *string    `json:"description,omitempty"`
	ID            *string    `json:"id,omitempty"`
	OrgID         *string    `json:"org_id,omitempty"`
	SharedWithOrg *bool      `json:"shared_with_org,omitempty"`
	Title         *string    `json:"title,omitempty"`
	UpdatedAt     *time.Time `json:"updated_at,omitempty"`
	UpdatedBy     *string    `json:"updated_by,omitempty"`
}

func (b Board) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *Board) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *Board) GetConfig() *Config {
	if o == nil {
		return nil
	}
	return o.Config
}

func (o *Board) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *Board) GetCreatedBy() *string {
	if o == nil {
		return nil
	}
	return o.CreatedBy
}

func (o *Board) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Board) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Board) GetOrgID() *string {
	if o == nil {
		return nil
	}
	return o.OrgID
}

func (o *Board) GetSharedWithOrg() *bool {
	if o == nil {
		return nil
	}
	return o.SharedWithOrg
}

func (o *Board) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *Board) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

func (o *Board) GetUpdatedBy() *string {
	if o == nil {
		return nil
	}
	return o.UpdatedBy
}
