// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk/internal/utils"
	"time"
)

type BoardSummary struct {
	CreatedAt     *time.Time `json:"created_at,omitempty"`
	CreatedBy     *string    `json:"created_by,omitempty"`
	Description   *string    `json:"description,omitempty"`
	ID            *string    `json:"id,omitempty"`
	OrgID         *string    `json:"org_id,omitempty"`
	SharedWith    []string   `json:"shared_with,omitempty"`
	SharedWithOrg *bool      `json:"shared_with_org,omitempty"`
	Title         *string    `json:"title,omitempty"`
	UpdatedAt     *time.Time `json:"updated_at,omitempty"`
	UpdatedBy     *string    `json:"updated_by,omitempty"`
}

func (b BoardSummary) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BoardSummary) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *BoardSummary) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *BoardSummary) GetCreatedBy() *string {
	if o == nil {
		return nil
	}
	return o.CreatedBy
}

func (o *BoardSummary) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *BoardSummary) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *BoardSummary) GetOrgID() *string {
	if o == nil {
		return nil
	}
	return o.OrgID
}

func (o *BoardSummary) GetSharedWith() []string {
	if o == nil {
		return nil
	}
	return o.SharedWith
}

func (o *BoardSummary) GetSharedWithOrg() *bool {
	if o == nil {
		return nil
	}
	return o.SharedWithOrg
}

func (o *BoardSummary) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *BoardSummary) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

func (o *BoardSummary) GetUpdatedBy() *string {
	if o == nil {
		return nil
	}
	return o.UpdatedBy
}
