// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// DynamicDateValue - Dynamic date keywords that resolve to actual dates at runtime
type DynamicDateValue string

const (
	DynamicDateValueToday       DynamicDateValue = "TODAY"
	DynamicDateValueTomorrow    DynamicDateValue = "TOMORROW"
	DynamicDateValueYesterday   DynamicDateValue = "YESTERDAY"
	DynamicDateValueInTheFuture DynamicDateValue = "IN_THE_FUTURE"
	DynamicDateValueInThePast   DynamicDateValue = "IN_THE_PAST"
	DynamicDateValueThisWeek    DynamicDateValue = "THIS_WEEK"
	DynamicDateValueNextWeek    DynamicDateValue = "NEXT_WEEK"
	DynamicDateValueLastWeek    DynamicDateValue = "LAST_WEEK"
	DynamicDateValueThisMonth   DynamicDateValue = "THIS_MONTH"
	DynamicDateValueNextMonth   DynamicDateValue = "NEXT_MONTH"
	DynamicDateValueLastMonth   DynamicDateValue = "LAST_MONTH"
)

func (e DynamicDateValue) ToPointer() *DynamicDateValue {
	return &e
}
func (e *DynamicDateValue) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "TODAY":
		fallthrough
	case "TOMORROW":
		fallthrough
	case "YESTERDAY":
		fallthrough
	case "IN_THE_FUTURE":
		fallthrough
	case "IN_THE_PAST":
		fallthrough
	case "THIS_WEEK":
		fallthrough
	case "NEXT_WEEK":
		fallthrough
	case "LAST_WEEK":
		fallthrough
	case "THIS_MONTH":
		fallthrough
	case "NEXT_MONTH":
		fallthrough
	case "LAST_MONTH":
		*e = DynamicDateValue(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DynamicDateValue: %v", v)
	}
}
