// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk/internal/utils"
)

// DataType - The data type of the field
type DataType string

const (
	DataTypeString  DataType = "string"
	DataTypeNumber  DataType = "number"
	DataTypeBoolean DataType = "boolean"
	DataTypeDate    DataType = "date"
)

func (e DataType) ToPointer() *DataType {
	return &e
}
func (e *DataType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "string":
		fallthrough
	case "number":
		fallthrough
	case "boolean":
		fallthrough
	case "date":
		*e = DataType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DataType: %v", v)
	}
}

type FilterItem struct {
	// The data type of the field
	DataType *DataType `json:"data_type,omitempty"`
	// The field key to filter on
	Key string `json:"key"`
	// The comparison operator for filtering
	Operator FilterOperator `json:"operator"`
	// The value to compare against - can be a single value (string, number, boolean, or dynamic date) or an array of values
	Value *ValueType `json:"value,omitempty"`
}

func (f FilterItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FilterItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, []string{"key", "operator"}); err != nil {
		return err
	}
	return nil
}

func (o *FilterItem) GetDataType() *DataType {
	if o == nil {
		return nil
	}
	return o.DataType
}

func (o *FilterItem) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *FilterItem) GetOperator() FilterOperator {
	if o == nil {
		return FilterOperator("")
	}
	return o.Operator
}

func (o *FilterItem) GetValue() *ValueType {
	if o == nil {
		return nil
	}
	return o.Value
}
