// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk/internal/utils"
)

type FilterGroupCombination string

const (
	FilterGroupCombinationAnd FilterGroupCombination = "AND"
	FilterGroupCombinationOr  FilterGroupCombination = "OR"
)

func (e FilterGroupCombination) ToPointer() *FilterGroupCombination {
	return &e
}
func (e *FilterGroupCombination) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "AND":
		fallthrough
	case "OR":
		*e = FilterGroupCombination(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FilterGroupCombination: %v", v)
	}
}

type FilterGroup struct {
	Combination FilterGroupCombination `json:"combination"`
	Items       []any                  `json:"items"`
}

func (f FilterGroup) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FilterGroup) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, []string{"combination", "items"}); err != nil {
		return err
	}
	return nil
}

func (o *FilterGroup) GetCombination() FilterGroupCombination {
	if o == nil {
		return FilterGroupCombination("")
	}
	return o.Combination
}

func (o *FilterGroup) GetItems() []any {
	if o == nil {
		return []any{}
	}
	return o.Items
}
