// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// FilterOperator - The comparison operator for filtering
type FilterOperator string

const (
	FilterOperatorEquals             FilterOperator = "EQUALS"
	FilterOperatorNotEquals          FilterOperator = "NOT_EQUALS"
	FilterOperatorEmpty              FilterOperator = "EMPTY"
	FilterOperatorNotEmpty           FilterOperator = "NOT_EMPTY"
	FilterOperatorContains           FilterOperator = "CONTAINS"
	FilterOperatorNotContains        FilterOperator = "NOT_CONTAINS"
	FilterOperatorIsOneOf            FilterOperator = "IS_ONE_OF"
	FilterOperatorIsNoneOf           FilterOperator = "IS_NONE_OF"
	FilterOperatorGreaterThan        FilterOperator = "GREATER_THAN"
	FilterOperatorLessThan           FilterOperator = "LESS_THAN"
	FilterOperatorGreaterThanOrEqual FilterOperator = "GREATER_THAN_OR_EQUAL"
	FilterOperatorLessThanOrEqual    FilterOperator = "LESS_THAN_OR_EQUAL"
)

func (e FilterOperator) ToPointer() *FilterOperator {
	return &e
}
func (e *FilterOperator) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "EQUALS":
		fallthrough
	case "NOT_EQUALS":
		fallthrough
	case "EMPTY":
		fallthrough
	case "NOT_EMPTY":
		fallthrough
	case "CONTAINS":
		fallthrough
	case "NOT_CONTAINS":
		fallthrough
	case "IS_ONE_OF":
		fallthrough
	case "IS_NONE_OF":
		fallthrough
	case "GREATER_THAN":
		fallthrough
	case "LESS_THAN":
		fallthrough
	case "GREATER_THAN_OR_EQUAL":
		fallthrough
	case "LESS_THAN_OR_EQUAL":
		*e = FilterOperator(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FilterOperator: %v", v)
	}
}
