// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk/internal/utils"
)

type FlowsQueryRequest struct {
	Filters *BoardFilter `json:"filters,omitempty"`
	From    *float64     `default:"0" json:"from"`
	Size    *float64     `default:"10" json:"size"`
	Sorting *Sorting     `json:"sorting,omitempty"`
}

func (f FlowsQueryRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FlowsQueryRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *FlowsQueryRequest) GetFilters() *BoardFilter {
	if o == nil {
		return nil
	}
	return o.Filters
}

func (o *FlowsQueryRequest) GetFrom() *float64 {
	if o == nil {
		return nil
	}
	return o.From
}

func (o *FlowsQueryRequest) GetSize() *float64 {
	if o == nil {
		return nil
	}
	return o.Size
}

func (o *FlowsQueryRequest) GetSorting() *Sorting {
	if o == nil {
		return nil
	}
	return o.Sorting
}
