// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk/internal/utils"
)

type FlowsQueryResult struct {
	AdditionalProperties any              `additionalProperties:"true" json:"-"`
	Hits                 *float64         `json:"hits,omitempty"`
	PageNumber           *float64         `json:"page_number,omitempty"`
	PageSize             *float64         `json:"page_size,omitempty"`
	Results              []map[string]any `json:"results,omitempty"`
	TotalPages           *float64         `json:"total_pages,omitempty"`
}

func (f FlowsQueryResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FlowsQueryResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FlowsQueryResult) GetAdditionalProperties() any {
	if f == nil {
		return nil
	}
	return f.AdditionalProperties
}

func (f *FlowsQueryResult) GetHits() *float64 {
	if f == nil {
		return nil
	}
	return f.Hits
}

func (f *FlowsQueryResult) GetPageNumber() *float64 {
	if f == nil {
		return nil
	}
	return f.PageNumber
}

func (f *FlowsQueryResult) GetPageSize() *float64 {
	if f == nil {
		return nil
	}
	return f.PageSize
}

func (f *FlowsQueryResult) GetResults() []map[string]any {
	if f == nil {
		return nil
	}
	return f.Results
}

func (f *FlowsQueryResult) GetTotalPages() *float64 {
	if f == nil {
		return nil
	}
	return f.TotalPages
}
