// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Swimlane struct {
	Filter           *BoardFilter `json:"filter,omitempty"`
	ID               any          `json:"id,omitempty"`
	Position         *float64     `json:"position,omitempty"`
	Title            *string      `json:"title,omitempty"`
	TitleChipVariant *string      `json:"title_chip_variant,omitempty"`
}

func (o *Swimlane) GetFilter() *BoardFilter {
	if o == nil {
		return nil
	}
	return o.Filter
}

func (o *Swimlane) GetID() any {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Swimlane) GetPosition() *float64 {
	if o == nil {
		return nil
	}
	return o.Position
}

func (o *Swimlane) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *Swimlane) GetTitleChipVariant() *string {
	if o == nil {
		return nil
	}
	return o.TitleChipVariant
}
