// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Swimlane struct {
	Filter           *BoardFilter `json:"filter,omitempty"`
	ID               *string      `json:"id,omitempty"`
	Position         *float64     `json:"position,omitempty"`
	Title            *string      `json:"title,omitempty"`
	TitleChipVariant *string      `json:"title_chip_variant,omitempty"`
}

func (s *Swimlane) GetFilter() *BoardFilter {
	if s == nil {
		return nil
	}
	return s.Filter
}

func (s *Swimlane) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *Swimlane) GetPosition() *float64 {
	if s == nil {
		return nil
	}
	return s.Position
}

func (s *Swimlane) GetTitle() *string {
	if s == nil {
		return nil
	}
	return s.Title
}

func (s *Swimlane) GetTitleChipVariant() *string {
	if s == nil {
		return nil
	}
	return s.TitleChipVariant
}
