// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk/internal/utils"
)

type FiveType string

const (
	FiveTypeStr              FiveType = "str"
	FiveTypeDynamicDateValue FiveType = "DynamicDateValue"
	FiveTypeNumber           FiveType = "number"
	FiveTypeBoolean          FiveType = "boolean"
)

type Five struct {
	Str              *string           `queryParam:"inline" name:"five"`
	DynamicDateValue *DynamicDateValue `queryParam:"inline" name:"five"`
	Number           *float64          `queryParam:"inline" name:"five"`
	Boolean          *bool             `queryParam:"inline" name:"five"`

	Type FiveType
}

func CreateFiveStr(str string) Five {
	typ := FiveTypeStr

	return Five{
		Str:  &str,
		Type: typ,
	}
}

func CreateFiveDynamicDateValue(dynamicDateValue DynamicDateValue) Five {
	typ := FiveTypeDynamicDateValue

	return Five{
		DynamicDateValue: &dynamicDateValue,
		Type:             typ,
	}
}

func CreateFiveNumber(number float64) Five {
	typ := FiveTypeNumber

	return Five{
		Number: &number,
		Type:   typ,
	}
}

func CreateFiveBoolean(boolean bool) Five {
	typ := FiveTypeBoolean

	return Five{
		Boolean: &boolean,
		Type:    typ,
	}
}

func (u *Five) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = FiveTypeStr
		return nil
	}

	var dynamicDateValue DynamicDateValue = DynamicDateValue("")
	if err := utils.UnmarshalJSON(data, &dynamicDateValue, "", true, nil); err == nil {
		u.DynamicDateValue = &dynamicDateValue
		u.Type = FiveTypeDynamicDateValue
		return nil
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		u.Number = &number
		u.Type = FiveTypeNumber
		return nil
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		u.Boolean = &boolean
		u.Type = FiveTypeBoolean
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Five", string(data))
}

func (u Five) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.DynamicDateValue != nil {
		return utils.MarshalJSON(u.DynamicDateValue, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	return nil, errors.New("could not marshal union type Five: all fields are null")
}

type ValueTypeType string

const (
	ValueTypeTypeStr              ValueTypeType = "str"
	ValueTypeTypeDynamicDateValue ValueTypeType = "DynamicDateValue"
	ValueTypeTypeNumber           ValueTypeType = "number"
	ValueTypeTypeBoolean          ValueTypeType = "boolean"
	ValueTypeTypeArrayOf5         ValueTypeType = "arrayOf5"
)

// ValueType - The value to compare against - can be a single value (string, number, boolean, or dynamic date) or an array of values
type ValueType struct {
	Str              *string           `queryParam:"inline" name:"ValueType"`
	DynamicDateValue *DynamicDateValue `queryParam:"inline" name:"ValueType"`
	Number           *float64          `queryParam:"inline" name:"ValueType"`
	Boolean          *bool             `queryParam:"inline" name:"ValueType"`
	ArrayOf5         []Five            `queryParam:"inline" name:"ValueType"`

	Type ValueTypeType
}

func CreateValueTypeStr(str string) ValueType {
	typ := ValueTypeTypeStr

	return ValueType{
		Str:  &str,
		Type: typ,
	}
}

func CreateValueTypeDynamicDateValue(dynamicDateValue DynamicDateValue) ValueType {
	typ := ValueTypeTypeDynamicDateValue

	return ValueType{
		DynamicDateValue: &dynamicDateValue,
		Type:             typ,
	}
}

func CreateValueTypeNumber(number float64) ValueType {
	typ := ValueTypeTypeNumber

	return ValueType{
		Number: &number,
		Type:   typ,
	}
}

func CreateValueTypeBoolean(boolean bool) ValueType {
	typ := ValueTypeTypeBoolean

	return ValueType{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateValueTypeArrayOf5(arrayOf5 []Five) ValueType {
	typ := ValueTypeTypeArrayOf5

	return ValueType{
		ArrayOf5: arrayOf5,
		Type:     typ,
	}
}

func (u *ValueType) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = ValueTypeTypeStr
		return nil
	}

	var dynamicDateValue DynamicDateValue = DynamicDateValue("")
	if err := utils.UnmarshalJSON(data, &dynamicDateValue, "", true, nil); err == nil {
		u.DynamicDateValue = &dynamicDateValue
		u.Type = ValueTypeTypeDynamicDateValue
		return nil
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		u.Number = &number
		u.Type = ValueTypeTypeNumber
		return nil
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		u.Boolean = &boolean
		u.Type = ValueTypeTypeBoolean
		return nil
	}

	var arrayOf5 []Five = []Five{}
	if err := utils.UnmarshalJSON(data, &arrayOf5, "", true, nil); err == nil {
		u.ArrayOf5 = arrayOf5
		u.Type = ValueTypeTypeArrayOf5
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ValueType", string(data))
}

func (u ValueType) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.DynamicDateValue != nil {
		return utils.MarshalJSON(u.DynamicDateValue, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.ArrayOf5 != nil {
		return utils.MarshalJSON(u.ArrayOf5, "", true)
	}

	return nil, errors.New("could not marshal union type ValueType: all fields are null")
}
