// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk/internal/utils"
)

type FiveType string

const (
	FiveTypeStr              FiveType = "str"
	FiveTypeDynamicDateValue FiveType = "DynamicDateValue"
	FiveTypeNumber           FiveType = "number"
	FiveTypeBoolean          FiveType = "boolean"
)

type Five struct {
	Str              *string           `queryParam:"inline,name=five"`
	DynamicDateValue *DynamicDateValue `queryParam:"inline,name=five"`
	Number           *float64          `queryParam:"inline,name=five"`
	Boolean          *bool             `queryParam:"inline,name=five"`

	Type FiveType
}

func CreateFiveStr(str string) Five {
	typ := FiveTypeStr

	return Five{
		Str:  &str,
		Type: typ,
	}
}

func CreateFiveDynamicDateValue(dynamicDateValue DynamicDateValue) Five {
	typ := FiveTypeDynamicDateValue

	return Five{
		DynamicDateValue: &dynamicDateValue,
		Type:             typ,
	}
}

func CreateFiveNumber(number float64) Five {
	typ := FiveTypeNumber

	return Five{
		Number: &number,
		Type:   typ,
	}
}

func CreateFiveBoolean(boolean bool) Five {
	typ := FiveTypeBoolean

	return Five{
		Boolean: &boolean,
		Type:    typ,
	}
}

func (u *Five) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FiveTypeStr,
			Value: &str,
		})
	}

	var dynamicDateValue DynamicDateValue = DynamicDateValue("")
	if err := utils.UnmarshalJSON(data, &dynamicDateValue, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FiveTypeDynamicDateValue,
			Value: &dynamicDateValue,
		})
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FiveTypeNumber,
			Value: &number,
		})
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FiveTypeBoolean,
			Value: &boolean,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Five", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestCandidate(candidates)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Five", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(FiveType)
	switch best.Type {
	case FiveTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case FiveTypeDynamicDateValue:
		u.DynamicDateValue = best.Value.(*DynamicDateValue)
		return nil
	case FiveTypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	case FiveTypeBoolean:
		u.Boolean = best.Value.(*bool)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Five", string(data))
}

func (u Five) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.DynamicDateValue != nil {
		return utils.MarshalJSON(u.DynamicDateValue, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	return nil, errors.New("could not marshal union type Five: all fields are null")
}

type ValueTypeType string

const (
	ValueTypeTypeStr              ValueTypeType = "str"
	ValueTypeTypeDynamicDateValue ValueTypeType = "DynamicDateValue"
	ValueTypeTypeNumber           ValueTypeType = "number"
	ValueTypeTypeBoolean          ValueTypeType = "boolean"
	ValueTypeTypeArrayOf5         ValueTypeType = "arrayOf5"
)

// ValueType - The value to compare against - can be a single value (string, number, boolean, or dynamic date) or an array of values
type ValueType struct {
	Str              *string           `queryParam:"inline,name=ValueType"`
	DynamicDateValue *DynamicDateValue `queryParam:"inline,name=ValueType"`
	Number           *float64          `queryParam:"inline,name=ValueType"`
	Boolean          *bool             `queryParam:"inline,name=ValueType"`
	ArrayOf5         []Five            `queryParam:"inline,name=ValueType"`

	Type ValueTypeType
}

func CreateValueTypeStr(str string) ValueType {
	typ := ValueTypeTypeStr

	return ValueType{
		Str:  &str,
		Type: typ,
	}
}

func CreateValueTypeDynamicDateValue(dynamicDateValue DynamicDateValue) ValueType {
	typ := ValueTypeTypeDynamicDateValue

	return ValueType{
		DynamicDateValue: &dynamicDateValue,
		Type:             typ,
	}
}

func CreateValueTypeNumber(number float64) ValueType {
	typ := ValueTypeTypeNumber

	return ValueType{
		Number: &number,
		Type:   typ,
	}
}

func CreateValueTypeBoolean(boolean bool) ValueType {
	typ := ValueTypeTypeBoolean

	return ValueType{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateValueTypeArrayOf5(arrayOf5 []Five) ValueType {
	typ := ValueTypeTypeArrayOf5

	return ValueType{
		ArrayOf5: arrayOf5,
		Type:     typ,
	}
}

func (u *ValueType) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ValueTypeTypeStr,
			Value: &str,
		})
	}

	var dynamicDateValue DynamicDateValue = DynamicDateValue("")
	if err := utils.UnmarshalJSON(data, &dynamicDateValue, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ValueTypeTypeDynamicDateValue,
			Value: &dynamicDateValue,
		})
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ValueTypeTypeNumber,
			Value: &number,
		})
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ValueTypeTypeBoolean,
			Value: &boolean,
		})
	}

	var arrayOf5 []Five = []Five{}
	if err := utils.UnmarshalJSON(data, &arrayOf5, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ValueTypeTypeArrayOf5,
			Value: arrayOf5,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ValueType", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestCandidate(candidates)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ValueType", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ValueTypeType)
	switch best.Type {
	case ValueTypeTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case ValueTypeTypeDynamicDateValue:
		u.DynamicDateValue = best.Value.(*DynamicDateValue)
		return nil
	case ValueTypeTypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	case ValueTypeTypeBoolean:
		u.Boolean = best.Value.(*bool)
		return nil
	case ValueTypeTypeArrayOf5:
		u.ArrayOf5 = best.Value.([]Five)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ValueType", string(data))
}

func (u ValueType) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.DynamicDateValue != nil {
		return utils.MarshalJSON(u.DynamicDateValue, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.ArrayOf5 != nil {
		return utils.MarshalJSON(u.ArrayOf5, "", true)
	}

	return nil, errors.New("could not marshal union type ValueType: all fields are null")
}
