// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/provider/typeconvert"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-kanban/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"
)

func (r *KanbanResourceModel) RefreshFromSharedBoard(ctx context.Context, resp *shared.Board) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if resp.Config == nil {
			r.Config = nil
		} else {
			r.Config = &tfTypes.Config{}
			if resp.Config.BoardFilter == nil {
				r.Config.BoardFilter = nil
			} else {
				r.Config.BoardFilter = &tfTypes.BoardFilter{}
				r.Config.BoardFilter.Combination = types.StringValue(string(resp.Config.BoardFilter.Combination))
				r.Config.BoardFilter.Items = []tfTypes.Items{}

				for _, itemsItem := range resp.Config.BoardFilter.Items {
					var items tfTypes.Items

					if itemsItem.Any != nil {
						anyResult, _ := json.Marshal(itemsItem.Any)
						items.Any = jsontypes.NewNormalizedValue(string(anyResult))
					}
					if itemsItem.FilterGroup != nil {
						items.FilterGroup = &tfTypes.FilterGroup{}
						items.FilterGroup.Combination = types.StringValue(string(itemsItem.FilterGroup.Combination))
						items.FilterGroup.Items = make([]jsontypes.Normalized, 0, len(itemsItem.FilterGroup.Items))
						for _, itemsItem1 := range itemsItem.FilterGroup.Items {
							var items1 jsontypes.Normalized

							items1Result, _ := json.Marshal(itemsItem1)
							items1 = jsontypes.NewNormalizedValue(string(items1Result))

							items.FilterGroup.Items = append(items.FilterGroup.Items, items1)
						}
					}

					r.Config.BoardFilter.Items = append(r.Config.BoardFilter.Items, items)
				}
			}
			if resp.Config.CardConfig == nil {
				r.Config.CardConfig = nil
			} else {
				r.Config.CardConfig = &tfTypes.CardConfig{}
				r.Config.CardConfig.Fields = make([]types.String, 0, len(resp.Config.CardConfig.Fields))
				for _, v := range resp.Config.CardConfig.Fields {
					r.Config.CardConfig.Fields = append(r.Config.CardConfig.Fields, types.StringValue(v))
				}
			}
			r.Config.Dataset = types.StringPointerValue(resp.Config.Dataset)
			r.Config.SearchQuery = types.StringPointerValue(resp.Config.SearchQuery)
			if resp.Config.Sorting == nil {
				r.Config.Sorting = nil
			} else {
				r.Config.Sorting = &tfTypes.Sorting{}
				if resp.Config.Sorting.Direction != nil {
					r.Config.Sorting.Direction = types.StringValue(string(*resp.Config.Sorting.Direction))
				} else {
					r.Config.Sorting.Direction = types.StringNull()
				}
				r.Config.Sorting.Field = types.StringValue(resp.Config.Sorting.Field)
			}
			r.Config.Swimlanes = []tfTypes.Swimlane{}

			for _, swimlanesItem := range resp.Config.Swimlanes {
				var swimlanes tfTypes.Swimlane

				if swimlanesItem.Filter == nil {
					swimlanes.Filter = nil
				} else {
					swimlanes.Filter = &tfTypes.BoardFilter{}
					swimlanes.Filter.Combination = types.StringValue(string(swimlanesItem.Filter.Combination))
					swimlanes.Filter.Items = []tfTypes.Items{}

					for _, itemsItem2 := range swimlanesItem.Filter.Items {
						var items2 tfTypes.Items

						if itemsItem2.Any != nil {
							anyResult1, _ := json.Marshal(itemsItem2.Any)
							items2.Any = jsontypes.NewNormalizedValue(string(anyResult1))
						}
						if itemsItem2.FilterGroup != nil {
							items2.FilterGroup = &tfTypes.FilterGroup{}
							items2.FilterGroup.Combination = types.StringValue(string(itemsItem2.FilterGroup.Combination))
							items2.FilterGroup.Items = make([]jsontypes.Normalized, 0, len(itemsItem2.FilterGroup.Items))
							for _, itemsItem3 := range itemsItem2.FilterGroup.Items {
								var items3 jsontypes.Normalized

								items3Result, _ := json.Marshal(itemsItem3)
								items3 = jsontypes.NewNormalizedValue(string(items3Result))

								items2.FilterGroup.Items = append(items2.FilterGroup.Items, items3)
							}
						}

						swimlanes.Filter.Items = append(swimlanes.Filter.Items, items2)
					}
				}
				swimlanes.ID = types.StringPointerValue(swimlanesItem.ID)
				swimlanes.Position = types.Float64PointerValue(swimlanesItem.Position)
				swimlanes.Title = types.StringPointerValue(swimlanesItem.Title)
				swimlanes.TitleChipVariant = types.StringPointerValue(swimlanesItem.TitleChipVariant)

				r.Config.Swimlanes = append(r.Config.Swimlanes, swimlanes)
			}
		}
		r.CreatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreatedAt))
		r.CreatedBy = types.StringPointerValue(resp.CreatedBy)
		r.Description = types.StringPointerValue(resp.Description)
		r.ID = types.StringPointerValue(resp.ID)
		r.OrgID = types.StringPointerValue(resp.OrgID)
		r.Owners = make([]types.String, 0, len(resp.Owners))
		for _, v := range resp.Owners {
			r.Owners = append(r.Owners, types.StringValue(v))
		}
		r.SharedWith = make([]types.String, 0, len(resp.SharedWith))
		for _, v := range resp.SharedWith {
			r.SharedWith = append(r.SharedWith, types.StringValue(v))
		}
		r.SharedWithOrg = types.BoolPointerValue(resp.SharedWithOrg)
		r.Title = types.StringPointerValue(resp.Title)
		r.UpdatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.UpdatedAt))
		r.UpdatedBy = types.StringPointerValue(resp.UpdatedBy)
	}

	return diags
}

func (r *KanbanResourceModel) ToOperationsDeleteKanbanBoardRequest(ctx context.Context) (*operations.DeleteKanbanBoardRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var boardID string
	boardID = r.ID.ValueString()

	out := operations.DeleteKanbanBoardRequest{
		BoardID: boardID,
	}

	return &out, diags
}

func (r *KanbanResourceModel) ToOperationsGetKanbanBoardRequest(ctx context.Context) (*operations.GetKanbanBoardRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var boardID string
	boardID = r.ID.ValueString()

	out := operations.GetKanbanBoardRequest{
		BoardID: boardID,
	}

	return &out, diags
}

func (r *KanbanResourceModel) ToOperationsPatchKanbanBoardRequest(ctx context.Context) (*operations.PatchKanbanBoardRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	requestBody, requestBodyDiags := r.ToOperationsPatchKanbanBoardRequestBody(ctx)
	diags.Append(requestBodyDiags...)

	if diags.HasError() {
		return nil, diags
	}

	var boardID string
	boardID = r.ID.ValueString()

	out := operations.PatchKanbanBoardRequest{
		RequestBody: requestBody,
		BoardID:     boardID,
	}

	return &out, diags
}

func (r *KanbanResourceModel) ToOperationsPatchKanbanBoardRequestBody(ctx context.Context) (*operations.PatchKanbanBoardRequestBody, diag.Diagnostics) {
	var diags diag.Diagnostics

	description := new(string)
	if !r.Description.IsUnknown() && !r.Description.IsNull() {
		*description = r.Description.ValueString()
	} else {
		description = nil
	}
	owners := make([]string, 0, len(r.Owners))
	for _, ownersItem := range r.Owners {
		owners = append(owners, ownersItem.ValueString())
	}
	sharedWith := make([]string, 0, len(r.SharedWith))
	for _, sharedWithItem := range r.SharedWith {
		sharedWith = append(sharedWith, sharedWithItem.ValueString())
	}
	sharedWithOrg := new(bool)
	if !r.SharedWithOrg.IsUnknown() && !r.SharedWithOrg.IsNull() {
		*sharedWithOrg = r.SharedWithOrg.ValueBool()
	} else {
		sharedWithOrg = nil
	}
	title := new(string)
	if !r.Title.IsUnknown() && !r.Title.IsNull() {
		*title = r.Title.ValueString()
	} else {
		title = nil
	}
	out := operations.PatchKanbanBoardRequestBody{
		Description:   description,
		Owners:        owners,
		SharedWith:    sharedWith,
		SharedWithOrg: sharedWithOrg,
		Title:         title,
	}

	return &out, diags
}

func (r *KanbanResourceModel) ToSharedBoard(ctx context.Context) (*shared.Board, diag.Diagnostics) {
	var diags diag.Diagnostics

	var config *shared.Config
	if r.Config != nil {
		var boardFilter *shared.BoardFilter
		if r.Config.BoardFilter != nil {
			combination := shared.Combination(r.Config.BoardFilter.Combination.ValueString())
			items := make([]shared.Items, 0, len(r.Config.BoardFilter.Items))
			for _, itemsItem := range r.Config.BoardFilter.Items {
				if !itemsItem.Any.IsUnknown() && !itemsItem.Any.IsNull() {
					var anyVar interface{}
					_ = json.Unmarshal([]byte(itemsItem.Any.ValueString()), &anyVar)
					items = append(items, shared.Items{
						Any: &anyVar,
					})
				}
				if itemsItem.FilterGroup != nil {
					combination1 := shared.FilterGroupCombination(itemsItem.FilterGroup.Combination.ValueString())
					items1 := make([]interface{}, 0, len(itemsItem.FilterGroup.Items))
					for _, itemsItem1 := range itemsItem.FilterGroup.Items {
						var itemsTmp interface{}
						_ = json.Unmarshal([]byte(itemsItem1.ValueString()), &itemsTmp)
						items1 = append(items1, itemsTmp)
					}
					filterGroup := shared.FilterGroup{
						Combination: combination1,
						Items:       items1,
					}
					items = append(items, shared.Items{
						FilterGroup: &filterGroup,
					})
				}
			}
			boardFilter = &shared.BoardFilter{
				Combination: combination,
				Items:       items,
			}
		}
		var cardConfig *shared.CardConfig
		if r.Config.CardConfig != nil {
			fields := make([]string, 0, len(r.Config.CardConfig.Fields))
			for _, fieldsItem := range r.Config.CardConfig.Fields {
				fields = append(fields, fieldsItem.ValueString())
			}
			cardConfig = &shared.CardConfig{
				Fields: fields,
			}
		}
		dataset := new(string)
		if !r.Config.Dataset.IsUnknown() && !r.Config.Dataset.IsNull() {
			*dataset = r.Config.Dataset.ValueString()
		} else {
			dataset = nil
		}
		searchQuery := new(string)
		if !r.Config.SearchQuery.IsUnknown() && !r.Config.SearchQuery.IsNull() {
			*searchQuery = r.Config.SearchQuery.ValueString()
		} else {
			searchQuery = nil
		}
		var sorting *shared.Sorting
		if r.Config.Sorting != nil {
			direction := new(shared.Direction)
			if !r.Config.Sorting.Direction.IsUnknown() && !r.Config.Sorting.Direction.IsNull() {
				*direction = shared.Direction(r.Config.Sorting.Direction.ValueString())
			} else {
				direction = nil
			}
			var field string
			field = r.Config.Sorting.Field.ValueString()

			sorting = &shared.Sorting{
				Direction: direction,
				Field:     field,
			}
		}
		swimlanes := make([]shared.Swimlane, 0, len(r.Config.Swimlanes))
		for _, swimlanesItem := range r.Config.Swimlanes {
			var filter *shared.BoardFilter
			if swimlanesItem.Filter != nil {
				combination2 := shared.Combination(swimlanesItem.Filter.Combination.ValueString())
				items2 := make([]shared.Items, 0, len(swimlanesItem.Filter.Items))
				for _, itemsItem2 := range swimlanesItem.Filter.Items {
					if !itemsItem2.Any.IsUnknown() && !itemsItem2.Any.IsNull() {
						var any1 interface{}
						_ = json.Unmarshal([]byte(itemsItem2.Any.ValueString()), &any1)
						items2 = append(items2, shared.Items{
							Any: &any1,
						})
					}
					if itemsItem2.FilterGroup != nil {
						combination3 := shared.FilterGroupCombination(itemsItem2.FilterGroup.Combination.ValueString())
						items3 := make([]interface{}, 0, len(itemsItem2.FilterGroup.Items))
						for _, itemsItem3 := range itemsItem2.FilterGroup.Items {
							var itemsTmp1 interface{}
							_ = json.Unmarshal([]byte(itemsItem3.ValueString()), &itemsTmp1)
							items3 = append(items3, itemsTmp1)
						}
						filterGroup1 := shared.FilterGroup{
							Combination: combination3,
							Items:       items3,
						}
						items2 = append(items2, shared.Items{
							FilterGroup: &filterGroup1,
						})
					}
				}
				filter = &shared.BoardFilter{
					Combination: combination2,
					Items:       items2,
				}
			}
			id := new(string)
			if !swimlanesItem.ID.IsUnknown() && !swimlanesItem.ID.IsNull() {
				*id = swimlanesItem.ID.ValueString()
			} else {
				id = nil
			}
			position := new(float64)
			if !swimlanesItem.Position.IsUnknown() && !swimlanesItem.Position.IsNull() {
				*position = swimlanesItem.Position.ValueFloat64()
			} else {
				position = nil
			}
			title := new(string)
			if !swimlanesItem.Title.IsUnknown() && !swimlanesItem.Title.IsNull() {
				*title = swimlanesItem.Title.ValueString()
			} else {
				title = nil
			}
			titleChipVariant := new(string)
			if !swimlanesItem.TitleChipVariant.IsUnknown() && !swimlanesItem.TitleChipVariant.IsNull() {
				*titleChipVariant = swimlanesItem.TitleChipVariant.ValueString()
			} else {
				titleChipVariant = nil
			}
			swimlanes = append(swimlanes, shared.Swimlane{
				Filter:           filter,
				ID:               id,
				Position:         position,
				Title:            title,
				TitleChipVariant: titleChipVariant,
			})
		}
		config = &shared.Config{
			BoardFilter: boardFilter,
			CardConfig:  cardConfig,
			Dataset:     dataset,
			SearchQuery: searchQuery,
			Sorting:     sorting,
			Swimlanes:   swimlanes,
		}
	}
	createdAt := new(time.Time)
	if !r.CreatedAt.IsUnknown() && !r.CreatedAt.IsNull() {
		*createdAt, _ = time.Parse(time.RFC3339Nano, r.CreatedAt.ValueString())
	} else {
		createdAt = nil
	}
	createdBy := new(string)
	if !r.CreatedBy.IsUnknown() && !r.CreatedBy.IsNull() {
		*createdBy = r.CreatedBy.ValueString()
	} else {
		createdBy = nil
	}
	description := new(string)
	if !r.Description.IsUnknown() && !r.Description.IsNull() {
		*description = r.Description.ValueString()
	} else {
		description = nil
	}
	id1 := new(string)
	if !r.ID.IsUnknown() && !r.ID.IsNull() {
		*id1 = r.ID.ValueString()
	} else {
		id1 = nil
	}
	orgID := new(string)
	if !r.OrgID.IsUnknown() && !r.OrgID.IsNull() {
		*orgID = r.OrgID.ValueString()
	} else {
		orgID = nil
	}
	owners := make([]string, 0, len(r.Owners))
	for _, ownersItem := range r.Owners {
		owners = append(owners, ownersItem.ValueString())
	}
	sharedWith := make([]string, 0, len(r.SharedWith))
	for _, sharedWithItem := range r.SharedWith {
		sharedWith = append(sharedWith, sharedWithItem.ValueString())
	}
	sharedWithOrg := new(bool)
	if !r.SharedWithOrg.IsUnknown() && !r.SharedWithOrg.IsNull() {
		*sharedWithOrg = r.SharedWithOrg.ValueBool()
	} else {
		sharedWithOrg = nil
	}
	title1 := new(string)
	if !r.Title.IsUnknown() && !r.Title.IsNull() {
		*title1 = r.Title.ValueString()
	} else {
		title1 = nil
	}
	updatedAt := new(time.Time)
	if !r.UpdatedAt.IsUnknown() && !r.UpdatedAt.IsNull() {
		*updatedAt, _ = time.Parse(time.RFC3339Nano, r.UpdatedAt.ValueString())
	} else {
		updatedAt = nil
	}
	updatedBy := new(string)
	if !r.UpdatedBy.IsUnknown() && !r.UpdatedBy.IsNull() {
		*updatedBy = r.UpdatedBy.ValueString()
	} else {
		updatedBy = nil
	}
	out := shared.Board{
		Config:        config,
		CreatedAt:     createdAt,
		CreatedBy:     createdBy,
		Description:   description,
		ID:            id1,
		OrgID:         orgID,
		Owners:        owners,
		SharedWith:    sharedWith,
		SharedWithOrg: sharedWithOrg,
		Title:         title1,
		UpdatedAt:     updatedAt,
		UpdatedBy:     updatedBy,
	}

	return &out, diags
}
