// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/provider/typeconvert"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-kanban/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *KanbanDataSourceModel) RefreshFromSharedBoard(ctx context.Context, resp *shared.Board) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if resp.Config == nil {
			r.Config = nil
		} else {
			r.Config = &tfTypes.Config{}
			if resp.Config.BoardFilter == nil {
				r.Config.BoardFilter = nil
			} else {
				r.Config.BoardFilter = &tfTypes.BoardFilter{}
				r.Config.BoardFilter.Combination = types.StringValue(string(resp.Config.BoardFilter.Combination))
				r.Config.BoardFilter.Items = []tfTypes.Items{}

				for _, itemsItem := range resp.Config.BoardFilter.Items {
					var items tfTypes.Items

					if itemsItem.Any != nil {
						anyResult, _ := json.Marshal(itemsItem.Any)
						items.Any = jsontypes.NewNormalizedValue(string(anyResult))
					}
					if itemsItem.FilterGroup != nil {
						items.FilterGroup = &tfTypes.FilterGroup{}
						items.FilterGroup.Combination = types.StringValue(string(itemsItem.FilterGroup.Combination))
						items.FilterGroup.Items = make([]jsontypes.Normalized, 0, len(itemsItem.FilterGroup.Items))
						for _, itemsItem1 := range itemsItem.FilterGroup.Items {
							var items1 jsontypes.Normalized

							items1Result, _ := json.Marshal(itemsItem1)
							items1 = jsontypes.NewNormalizedValue(string(items1Result))

							items.FilterGroup.Items = append(items.FilterGroup.Items, items1)
						}
					}

					r.Config.BoardFilter.Items = append(r.Config.BoardFilter.Items, items)
				}
			}
			if resp.Config.CardConfig == nil {
				r.Config.CardConfig = nil
			} else {
				r.Config.CardConfig = &tfTypes.CardConfig{}
				r.Config.CardConfig.Fields = make([]types.String, 0, len(resp.Config.CardConfig.Fields))
				for _, v := range resp.Config.CardConfig.Fields {
					r.Config.CardConfig.Fields = append(r.Config.CardConfig.Fields, types.StringValue(v))
				}
			}
			r.Config.Dataset = types.StringPointerValue(resp.Config.Dataset)
			r.Config.SearchQuery = types.StringPointerValue(resp.Config.SearchQuery)
			if resp.Config.Sorting == nil {
				r.Config.Sorting = nil
			} else {
				r.Config.Sorting = &tfTypes.Sorting{}
				if resp.Config.Sorting.Direction != nil {
					r.Config.Sorting.Direction = types.StringValue(string(*resp.Config.Sorting.Direction))
				} else {
					r.Config.Sorting.Direction = types.StringNull()
				}
				r.Config.Sorting.Field = types.StringValue(resp.Config.Sorting.Field)
			}
			r.Config.Swimlanes = []tfTypes.Swimlane{}

			for _, swimlanesItem := range resp.Config.Swimlanes {
				var swimlanes tfTypes.Swimlane

				if swimlanesItem.Filter == nil {
					swimlanes.Filter = nil
				} else {
					swimlanes.Filter = &tfTypes.BoardFilter{}
					swimlanes.Filter.Combination = types.StringValue(string(swimlanesItem.Filter.Combination))
					swimlanes.Filter.Items = []tfTypes.Items{}

					for _, itemsItem2 := range swimlanesItem.Filter.Items {
						var items2 tfTypes.Items

						if itemsItem2.Any != nil {
							anyResult1, _ := json.Marshal(itemsItem2.Any)
							items2.Any = jsontypes.NewNormalizedValue(string(anyResult1))
						}
						if itemsItem2.FilterGroup != nil {
							items2.FilterGroup = &tfTypes.FilterGroup{}
							items2.FilterGroup.Combination = types.StringValue(string(itemsItem2.FilterGroup.Combination))
							items2.FilterGroup.Items = make([]jsontypes.Normalized, 0, len(itemsItem2.FilterGroup.Items))
							for _, itemsItem3 := range itemsItem2.FilterGroup.Items {
								var items3 jsontypes.Normalized

								items3Result, _ := json.Marshal(itemsItem3)
								items3 = jsontypes.NewNormalizedValue(string(items3Result))

								items2.FilterGroup.Items = append(items2.FilterGroup.Items, items3)
							}
						}

						swimlanes.Filter.Items = append(swimlanes.Filter.Items, items2)
					}
				}
				swimlanes.ID = types.StringPointerValue(swimlanesItem.ID)
				swimlanes.Position = types.Float64PointerValue(swimlanesItem.Position)
				swimlanes.Title = types.StringPointerValue(swimlanesItem.Title)
				swimlanes.TitleChipVariant = types.StringPointerValue(swimlanesItem.TitleChipVariant)

				r.Config.Swimlanes = append(r.Config.Swimlanes, swimlanes)
			}
		}
		r.CreatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreatedAt))
		r.CreatedBy = types.StringPointerValue(resp.CreatedBy)
		r.Description = types.StringPointerValue(resp.Description)
		r.ID = types.StringPointerValue(resp.ID)
		r.OrgID = types.StringPointerValue(resp.OrgID)
		if resp.Owners == nil {
			r.Owners = jsontypes.NewNormalizedNull()
		} else {
			ownersResult, _ := json.Marshal(resp.Owners)
			r.Owners = jsontypes.NewNormalizedValue(string(ownersResult))
		}
		if resp.SharedWith == nil {
			r.SharedWith = jsontypes.NewNormalizedNull()
		} else {
			sharedWithResult, _ := json.Marshal(resp.SharedWith)
			r.SharedWith = jsontypes.NewNormalizedValue(string(sharedWithResult))
		}
		r.SharedWithOrg = types.BoolPointerValue(resp.SharedWithOrg)
		r.Title = types.StringPointerValue(resp.Title)
		r.UpdatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.UpdatedAt))
		r.UpdatedBy = types.StringPointerValue(resp.UpdatedBy)
	}

	return diags
}

func (r *KanbanDataSourceModel) ToOperationsGetKanbanBoardRequest(ctx context.Context) (*operations.GetKanbanBoardRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var boardID string
	boardID = r.ID.ValueString()

	out := operations.GetKanbanBoardRequest{
		BoardID: boardID,
	}

	return &out, diags
}
