// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-kanban/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-kanban/internal/sdk"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &KanbanDataSource{}
var _ datasource.DataSourceWithConfigure = &KanbanDataSource{}

func NewKanbanDataSource() datasource.DataSource {
	return &KanbanDataSource{}
}

// KanbanDataSource is the data source implementation.
type KanbanDataSource struct {
	// Provider configured SDK client.
	client *sdk.SDK
}

// KanbanDataSourceModel describes the data model.
type KanbanDataSourceModel struct {
	Config        *tfTypes.Config      `tfsdk:"config"`
	CreatedAt     types.String         `tfsdk:"created_at"`
	CreatedBy     types.String         `tfsdk:"created_by"`
	Description   types.String         `tfsdk:"description"`
	ID            types.String         `tfsdk:"id"`
	OrgID         types.String         `tfsdk:"org_id"`
	Owners        jsontypes.Normalized `tfsdk:"owners"`
	SharedWith    jsontypes.Normalized `tfsdk:"shared_with"`
	SharedWithOrg types.Bool           `tfsdk:"shared_with_org"`
	Title         types.String         `tfsdk:"title"`
	UpdatedAt     types.String         `tfsdk:"updated_at"`
	UpdatedBy     types.String         `tfsdk:"updated_by"`
}

// Metadata returns the data source type name.
func (r *KanbanDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_kanban"
}

// Schema defines the schema for the data source.
func (r *KanbanDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Kanban DataSource",

		Attributes: map[string]schema.Attribute{
			"config": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"board_filter": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"combination": schema.StringAttribute{
								Computed: true,
							},
							"items": schema.ListNestedAttribute{
								Computed: true,
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"any": schema.StringAttribute{
											CustomType:  jsontypes.NormalizedType{},
											Computed:    true,
											Description: `Parsed as JSON.`,
										},
										"filter_group": schema.SingleNestedAttribute{
											Computed: true,
											Attributes: map[string]schema.Attribute{
												"combination": schema.StringAttribute{
													Computed: true,
												},
												"items": schema.ListAttribute{
													Computed:    true,
													ElementType: jsontypes.NormalizedType{},
												},
											},
										},
									},
								},
							},
						},
					},
					"card_config": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"fields": schema.ListAttribute{
								Computed:    true,
								ElementType: types.StringType,
							},
						},
					},
					"dataset": schema.StringAttribute{
						Computed: true,
					},
					"search_query": schema.StringAttribute{
						Computed: true,
					},
					"sorting": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"direction": schema.StringAttribute{
								Computed: true,
							},
							"field": schema.StringAttribute{
								Computed: true,
							},
						},
					},
					"swimlanes": schema.ListNestedAttribute{
						Computed: true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"filter": schema.SingleNestedAttribute{
									Computed: true,
									Attributes: map[string]schema.Attribute{
										"combination": schema.StringAttribute{
											Computed: true,
										},
										"items": schema.ListNestedAttribute{
											Computed: true,
											NestedObject: schema.NestedAttributeObject{
												Attributes: map[string]schema.Attribute{
													"any": schema.StringAttribute{
														CustomType:  jsontypes.NormalizedType{},
														Computed:    true,
														Description: `Parsed as JSON.`,
													},
													"filter_group": schema.SingleNestedAttribute{
														Computed: true,
														Attributes: map[string]schema.Attribute{
															"combination": schema.StringAttribute{
																Computed: true,
															},
															"items": schema.ListAttribute{
																Computed:    true,
																ElementType: jsontypes.NormalizedType{},
															},
														},
													},
												},
											},
										},
									},
								},
								"id": schema.StringAttribute{
									Computed: true,
								},
								"position": schema.Float64Attribute{
									Computed: true,
								},
								"title": schema.StringAttribute{
									Computed: true,
								},
								"title_chip_variant": schema.StringAttribute{
									Computed: true,
								},
							},
						},
					},
				},
			},
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"created_by": schema.StringAttribute{
				Computed: true,
			},
			"description": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"org_id": schema.StringAttribute{
				Computed: true,
			},
			"owners": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: `Array of user IDs who have full ownership rights for this board (view, edit, delete). Parsed as JSON.`,
			},
			"shared_with": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: `Parsed as JSON.`,
			},
			"shared_with_org": schema.BoolAttribute{
				Computed: true,
			},
			"title": schema.StringAttribute{
				Computed: true,
			},
			"updated_at": schema.StringAttribute{
				Computed: true,
			},
			"updated_by": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

func (r *KanbanDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.SDK)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.SDK, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *KanbanDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *KanbanDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsGetKanbanBoardRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Kanban.GetKanbanBoard(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.Board != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedBoard(ctx, res.Board)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
