// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type BoardFilter struct {
	Combination types.String `tfsdk:"combination"`
	Items       []Items      `tfsdk:"items"`
}
