// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type CardConfig struct {
	Fields []types.String `tfsdk:"fields"`
}
