// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type Config struct {
	BoardFilter *BoardFilter `tfsdk:"board_filter"`
	CardConfig  *CardConfig  `tfsdk:"card_config"`
	Dataset     types.String `tfsdk:"dataset"`
	SearchQuery types.String `tfsdk:"search_query"`
	Sorting     *Sorting     `tfsdk:"sorting"`
	Swimlanes   []Swimlane   `tfsdk:"swimlanes"`
}
