// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type FilterItem struct {
	DataType types.String `tfsdk:"data_type"`
	Key      types.String `tfsdk:"key"`
	Operator types.String `tfsdk:"operator"`
	Value    *ValueType   `tfsdk:"value"`
}
