// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type FilterGroup struct {
	Combination types.String           `tfsdk:"combination"`
	Items       []jsontypes.Normalized `tfsdk:"items"`
}
