// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
)

type Items struct {
	Any         jsontypes.Normalized `queryParam:"inline" tfsdk:"any" tfPlanOnly:"true"`
	FilterGroup *FilterGroup         `queryParam:"inline" tfsdk:"filter_group" tfPlanOnly:"true"`
}
