// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type Items struct {
	FilterGroup *FilterGroup `queryParam:"inline" tfsdk:"filter_group" tfPlanOnly:"true"`
	FilterItem  *FilterItem  `queryParam:"inline" tfsdk:"filter_item" tfPlanOnly:"true"`
}
