// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type Sorting struct {
	Direction types.String `tfsdk:"direction"`
	Field     types.String `tfsdk:"field"`
}
