// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ValueType struct {
	Str              types.String  `queryParam:"inline" tfsdk:"str" tfPlanOnly:"true"`
	Number           types.Float64 `queryParam:"inline" tfsdk:"number" tfPlanOnly:"true"`
	Boolean          types.Bool    `queryParam:"inline" tfsdk:"boolean" tfPlanOnly:"true"`
	ArrayOfFive      []Five        `queryParam:"inline" tfsdk:"array_of_five" tfPlanOnly:"true"`
	DynamicDateValue types.String  `queryParam:"inline" tfsdk:"dynamic_date_value" tfPlanOnly:"true"`
}
